### ISSUE TITLE
Normalisation to construct bounds vs data bounds

### ISSUE THREAD

**Issue by jamessteeleii** [saudiwin/ordbetareg_pack#2] opened 2022-03-13 11:50 UTC
Love the package and approach - stumbling across it has been perfect because I often deal with bounded continuous data.

Just following up from twitter exchange (https://twitter.com/JamesSteeleII/status/1502963025925619712?s=20&t=cYgXau8Y7vsb0LPlkF2tLw).

I have the case where my construct DV is theoretically bounded on a particular interval (say [0,1]) and so could take values of 0, but because of experimental design never will take that value and so it does not appear in the data despite being possible. It seems as though the normalize function treats whatever the lowest value in the data is and treats that as the lowest bound to normalize to (and conversely the highest value for the upper bound). An easy fix as you noted was to add a row with the lowest bound value and NA for covariates (and conversely that could be done in instances where the highest construct value isn't in the data I suppose). But would be great if this could be specified in the normalize function (and ordbetareg function) itself... something like telling it what the construct bounds are so it can normalize observed values to that interval. 

Thanks again!

**Comment by saudiwin** [comment] 2022-05-06 07:24
I have pushed commits that allow you to do this with the `true_bounds` option. The function also reports what bounds its using so that's clear to the user. Won't be on CRAN for a while but you can get it from Github. 

did you manage to get pp_check to work? I couldn't reproduce that error on my end. If you can make it reproducible, I can try to figure it out.

**Comment by jamessteeleii** [comment] 2022-05-09 11:37
Amazing - thanks!

Unfortunately, I've not been able to figure it out or create a reprex, plus not had time to try a full uninstall/reinstall to see if that solves anything as it seems to be a local issue. Once I get a chance I'll let you know.

**Comment by saudiwin** [comment] 2022-08-16 13:39
closing this issue as the normalization issue is resolved

**Closed by saudiwin** 2022-08-16 13:39 UTC
